### ISSUE TITLE
Error cuando un kanji y un componente tienen la misma clave.

### ISSUE THREAD

**Issue by sandevins** [eoi-japones/kanji-data#71]
En ocasiones un kanji y un componente tienen la misma clave.

Ejemplo:
- 彡: forma (componente)
- 形: forma (kanji)

Una posible solución es que la clave del componente tenga un asterisco delante (*forma).

- [ ] Buscar una forma de buscar componentes y kanjis con la misma clave

**Comment by frmadem** [comment]
@sandevins @davconde @ascaseiro qué os parece emplear un signo distintitivo para denotar un componente (de tipo solo_componente) que coincide con un compuesto real:

1. Forma 形
2. *Forma: 彡

De esta manera se pueden indexar sin problema, y en el sistema de búsqueda (kanji-api) se permite la búsqueda (elimando el asterisco)

**Comment by davconde** [comment]
A min paréceme mellor. Entendo que debería ir xa integrado no formulario de introducción de kanjis ao elexir só componente, non?
